insert into ADDRESS(aid, address_line1, city, state, zipcode) values (11, 'addressline1', 'city1', 'state', 2077);
insert into ADDRESS(aid, address_line1, city, state, zipcode) values (12, 'addressline2', 'city1', 'state', 2078);
insert into ADDRESS(aid, address_line1, city, state, zipcode) values (13, 'addressline3', 'city1', 'state', 2079);
insert into ADDRESS(aid, address_line1, city, state, zipcode) values (14, 'addressline3', 'city1', 'state', 2080);
insert into ADDRESS(aid, address_line1, city, state, zipcode) values (15, 'addressline3', 'city1', 'state', 2080);
insert into CONTACT(id, first_name, last_name, contact_number, activate_flag, aid) values (1, 'simi', 'gopal', '11111', 0, 11);
insert into CONTACT(id, first_name, last_name, contact_number, activate_flag, aid) values (2, 'simi', 'gopal', '222222', 0, 11);
insert into CONTACT(id, first_name, last_name, contact_number, activate_flag, aid) values (3, 'kunju','sreeju', '333333', 0, 12);
insert into CONTACT(id, first_name, last_name, contact_number, activate_flag, aid) values (4, 'sreeju', 'sn', '444444', 0, 13);
insert into CONTACT(id, first_name, last_name, contact_number, activate_flag, aid) values (5, 'tittu', 'sona', '555555', 0, 14);